#!/bin/bash
set -e
set -o pipefail

# set up where everything is
# not quite sure if we neeed ever to deal with symlinks but if we do this is it:
# BAO_BASE_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"

export BAO_BASE="$(dirname "$0")"
export BAO_BASE_DIR="$(cd ${BAO_BASE} && pwd)"
export BAO_BASE_BIN_DIR="$BAO_BASE_DIR/bin"
export BAO_BASE_LIB_DIR="$BAO_BASE_BIN_DIR/modules"

# then call the script
# we don't support calling python/node/etc. scripts here because we don't know
# what version of python/node/etc. the script requires. That is the job of the
# script we are about to call, passing all the given parameters
SCRIPT="$BAO_BASE_BIN_DIR/$1"
shift
echo "Running $SCRIPT $@"
"$SCRIPT" "$@"
