[tool.poetry]
name = "bao-base-bin-modules-slither"
version = "0.1.0"
description = "Fallback dependencies for scripts"
authors = ["rootminus0x1"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.13"
solc-select = "^1.0.4"
slither-analyzer = "^0.10.4"
