name: Test Scripting
description: "runs all the tests for bash scripts"

# secrets:
#   DEFAULT_MAINNET_RPC_URL:
#     description: "default API URL for accessing blockchain service"
#     required: false
inputs:
  # os:
  #   description: "Operating system to test"
  #   required: true
  #   type: string
  foundry:
    description: "Foundry version to test"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check Environment
      shell: bash
      run: |
        echo "runner.os=${{ runner.os }}"
        python3 -c "import platform; info = f'{platform.system()} {platform.release()} {platform.version()} {platform.machine()}'; print('-' * len(info)); print(info); print('-' * len(info))"

    - name: Install recent python
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
    - shell: bash
      run: |
        which python3
        python3 --version

    - name: Install Poetry (python package manager)
      uses: snok/install-poetry@v1
      with:
        version: 1.8.5
    - shell: bash
      run: |
        which poetry
        poetry --version

    # we install foundry because some scripts check for it's existence
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: ${{ inputs.FOUNDRY }}
    - shell: bash
      run: |
        forge --version

    - name: Install project dependencies
      shell: bash
      run: |
        yarn

    - name: Run Bash Tests
      shell: bash
      run: |
        yarn test:bash
      id: bats

    - name: Check for changed repo files
      shell: bash
      run: |
        yarn git-diffs
