name: Local CI foundry

on:
  workflow_dispatch:
    inputs:
      os:
        description: "Operating system to test"
        required: true
        type: string
      foundry:
        description: "Foundry version to test"
        required: true
        type: string

#env:
# FOUNDRY_PROFILE: ci

jobs:
  test_foundry:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Run Bao-base CI actions
        uses: $BAO_BASE_DIR/.github/actions/test-foundry
        with:
          foundry: ${{ inputs.foundry }}
