name: CI

on:
  workflow_call:

jobs:
  test_foundry_matrix:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            foundry: nightly
          - os: ubuntu-22.04
            foundry: v0.3.0
          - os: ubuntu-22.04
            foundry: nightly-233bff2f8ef1f958e1676048c85a2bc37efa2241

          - os: macos-latest
            foundry: nightly
          - os: macos-14
            foundry: v0.3.0

          - os: windows-latest
            foundry: nightly
          - os: windows-2022
            foundry: v0.3.0
      fail-fast: false # ensure all jobs run even if one fails

    name: Bao Foundry project
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run project
        uses: ./.github/workflows/bao-foundry-project.yml
        with:
          foundry: ${{ matrix.foundry }}
          os: ${{ matrix.os }}
