name: CI

on:
  workflow_call:
    secrets:
      API_KEY:
        description: "API key for accessing service"
        required: false

env:
  FOUNDRY_PROFILE: ci

jobs:
  solidity_code_check:
    strategy:
      matrix:
        os: [windows-latest] # ubuntu-latest, ubuntu-22.04, macos-13, windows-2022]
        foundry: [v0.3.0] #, nightly, nightly-233bff2f8ef1f958e1676048c85a2bc37efa2241]
      fail-fast: false # ensure all jobs run even if one fails

    name: Bao Foundry project
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check Environment
        run: |
          echo "runner.os=${{ runner.os }}"
          python3 -c "import platform; info = f'{platform.system()} {platform.release()} {platform.version()} {platform.machine()}'; print('-' * len(info)); print(info); print('-' * len(info))"

      - name: Install recent python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - run: |
          python3 --version

      - name: Install Poetry (python package manager)
        uses: snok/install-poetry@v1

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: ${{ matrix.foundry }}
      - run: |
          forge --version

      - name: Install project dependencies
        run: |
          yarn

      - name: Run Prettier
        run: |
          yarn fmt:check
        id: fmt

      - name: Run Solhint
        run: |
          yarn lint
        id: lint

      - name: Run Slither
        run: |
          yarn slither
        id: slither

      - name: Run Forge build
        run: |
          yarn sizes
        id: build

      - name: Run Forge tests
        env:
          MAINNET_RPC_URL_BASE: https://eth-mainnet.g.alchemy.com/v2
          MAINNET_RPC_API_KEY: ${{secrets.API_KEY}}
        run: |
          if [ -n "$MAINNET_RPC_API_KEY" ]; then
              export MAINNET_RPC_URL=${MAINNET_RPC_URL_BASE}/${MAINNET_RPC_API_KEY}
          fi
          yarn test
          yarn coverage
          yarn gas
        id: test

      - name: Check for changed repo files
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Uncommitted changes detected:"
            git status --porcelain
            exit 1
          fi
