name: CI

on:
  workflow_call:
    secrets:
      API_KEY:
        description: "API key for accessing service"
        required: false

env:
  FOUNDRY_PROFILE: ci

jobs:
  solidity_code_check:
    strategy:
      fail-fast: true

    name: Bao Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install system tools
        run: |
          sudo apt-get update
          echo sudo apt-get install -y software-properties-common
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          sudo apt update
          sudo apt install -y python3.11
          python3 --version
          curl -sSL https://install.python-poetry.org | python3 -
          echo $PATH
          export PATH="$HOME/.local/bin:$PATH"
          poetry --version

      - name: Install project dependencies
        run: |
          forge --version
          yarn

      - name: Run Prettier
        run: |
          yarn fmt:check
        id: fmt

      - name: Run Solhint
        run: |
          yarn lint
        id: lint

      - name: Run Slither
        run: |
          python3 --version
          poetry --version
          poetry --help
          yarn slither
        id: slither

      - name: Run Forge build
        run: |
          yarn sizes
        id: build

      - name: Run Forge tests
        env:
          MAINNET_RPC_URL_BASE: https://eth-mainnet.g.alchemy.com/v2
          MAINNET_RPC_API_KEY: ${{secrets.API_KEY}}
        run: |
          if [ -n "$MAINNET_RPC_API_KEY" ]; then
              export MAINNET_RPC_URL=${MAINNET_RPC_URL_BASE}/${MAINNET_RPC_API_KEY}
          fi
          yarn test
          yarn coverage
          yarn gas
        id: test
