name: CI

on:
  workflow_call:
    secrets:
      API_KEY:
        description: "API key for accessing service"
        required: false

env:
  FOUNDRY_PROFILE: ci

jobs:
  solidity_code_check:
    strategy:
      fail-fast: true

    name: Bao Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: |
          forge --version
          yarn
          yarn install:slither

      - name: Run Prettier
        run: |
          yarn fmt:check
        id: fmt

      - name: Run Solhint
        run: |
          yarn lint
        id: lint

      - name: Run Slither
        run: |
          yarn slither
        id: slither

      - name: Run Forge build
        run: |
          forge build --sizes
        id: build

      - name: Run Forge tests
        env:
          MAINNET_RPC_URL_BASE: https://eth-mainnet.g.alchemy.com/v2
          MAINNET_RPC_API_KEY: ${{secrets.API_KEY}}
        run: |
          if [ -n "$MAINNET_RPC_API_KEY" ]; then
              export MAINNET_RPC_URL=${MAINNET_RPC_URL_BASE}/${MAINNET_RPC_API_KEY}
          fi
          yarn test
        id: test
