name: CI

on:
  workflow_call:
    secrets:
      API_KEY:
        description: "API key for accessing service"
        required: false

env:
  FOUNDRY_PROFILE: ci

jobs:
  solidity_code_check:
    strategy:
      fail-fast: true

    name: Bao Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        env:
          MAINNET_RPC_URL: https://eth-mainnet.g.alchemy.com/v2/${{secrets.API_KEY}}
        run: |
          echo "Using API key in a script"
          forge --version
          yarn
          yarn install:slither

      - name: Run Prettier
        run: |
          yarn fmt:check
        id: fmt

      - name: Run Solhint
        run: |
          yarn lint
        id: lint

      - name: Run Slither
        run: |
          yarn slither
        id: slither

      - name: Run Forge build
        run: |
          forge build --sizes
        id: build

      - name: Run Forge tests
        env:
          MAINNET_RPC_URL: https://eth-mainnet.g.alchemy.com/v2/${{secrets.ALCHEMY_KEY}}
        run: |
          yarn test
        id: test
