name: test-scripting

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  MAINNET_RPC_URL: https://eth-mainnet.g.alchemy.com/v2/${{ secrets.ALCHEMY_KEY }}

jobs:
  test_foundry_matrix:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            foundry: v0.3.0

          - os: macos-14
            foundry: v0.3.0

          - os: windows-2022
            foundry: v0.3.0
      fail-fast: false # ensure all jobs run even if one fails

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Run Bao-base CI actions
        uses: ./.github/actions/test-scripting
        with:
          foundry: ${{ matrix.foundry }}
