name: test-foundry-latest

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  MAINNET_RPC_URL: https://eth-mainnet.g.alchemy.com/v2/${{ secrets.ALCHEMY_KEY }}

jobs:
  test_foundry_os:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            foundry: nightly

          - os: macos-latest
            foundry: nightly

          - os: windows-latest
            foundry: nightly

      fail-fast: false # ensure all jobs run even if one fails

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Run Bao-base CI actions
        uses: ./.github/actions/test-foundry
        with:
          foundry: ${{ matrix.foundry }}
