name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:
    secrets:
      ALCHEMY_KEY:
        description: "API KEY for accessing the ALchemy blockchain service"
        required: false

jobs:
  test_foundry_matrix:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            foundry: nightly
          - os: ubuntu-22.04
            foundry: v0.3.0
          - os: ubuntu-22.04
            foundry: nightly-233bff2f8ef1f958e1676048c85a2bc37efa2241

          - os: macos-latest
            foundry: nightly
          - os: macos-14
            foundry: v0.3.0

          - os: windows-latest
            foundry: nightly
          - os: windows-2022
            foundry: v0.3.0
      fail-fast: false # ensure all jobs run even if one fails

    uses: ./.github/workflows/test-foundry.yml
    secrets:
      DEFAULT_MAINNET_RPC_URL: https://eth-mainnet.g.alchemy.com/v2/${{ secrets.ALCHEMY_KEY }}
    with:
      os: ${{ matrix.os }}
      foundry: ${{ matrix.foundry }}
